png("plot1.png", width = 480, height = 480, unit = "px")
ePower <- read.table("household_power_consumption.txt", na.strings = "?", skip = 66637, nrows = (69517-66637),sep = ';',col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
ePower$Date <- paste(ePower$Date, ePower$Time)
ePower$Date <- as.Date(ePower$Date, format = "%d/%m/%Y %H:%M:%S")
hist(ePower$Global_active_power,xlab = "Global Active Power (kilowatts)", col = "red", main = "Global Active Power", yaxt = "n")
axis(2, at=c(0,200,400,600,800,1000,1200),labels = c("0","200","400","600","800","1000","1200"))
dev.off()