png("plot2.png", width = 480, height = 480, unit = "px")
ePower <- read.table("household_power_consumption.txt", na.strings = "?", skip = 66637, nrows = (69517-66637),sep = ';',col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"))
ePower$Date <- paste(ePower$Date, ePower$Time)
ePower$Date <- strptime(ePower$Date, format = "%d/%m/%Y %H:%M:%S")
par(mar = c(2,4,2,4))
plot(ePower$Date,ePower$Global_active_power, type = "l", xlab = '',ylab = 'Global Active Power (kilowatts)')
dev.off()